### ISSUE TITLE
Broken build in Gradle 2.11

### ISSUE THREAD

**Issue by danielfernandez** [ratpack/ratpack#924]
This is not exactly a RatPack issue, but it is to note that RatPack build is broken using Gradle 2.11 due to this issue at the ShadowJar plugin: johnrengelman/shadow#185

This can be reproduced by simply cloning the ratpack repository and executing a `gradle` build using version 2.11.

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.java.archives.internal.DefaultManifest.<init>(Lorg/gradle/api/internal/file/FileResolver;)V
	at com.github.jengelman.gradle.plugins.shadow.tasks.DefaultInheritManifest.<init>(DefaultInheritManifest.groovy:15)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.<init>(ShadowJar.java:44)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated.<init>(Unknown Source)
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
```

**Comment by danhyun** [comment]
This is fixed in shadow version 1.2.3
https://github.com/johnrengelman/shadow/issues/177
